import{S as c}from"./assets/vendor-CgTBfC_f.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))g(e);new MutationObserver(e=>{for(const i of e)if(i.type==="childList")for(const s of i.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&g(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const i={};return e.integrity&&(i.integrity=e.integrity),e.referrerPolicy&&(i.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?i.credentials="include":e.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function g(e){if(e.ep)return;e.ep=!0;const i=n(e);fetch(e.href,i)}})();const m=[{preview:"/goit-js-hw-09/img/1.jpg",original:"/goit-js-hw-09/img/1.jpg",description:"Image 1 description"},{preview:"img/2.jpg",original:"img/2.jpg",description:"Image 2 description"},{preview:"img/3.jpg",original:"img/3.jpg",description:"Image 3 description"},{preview:"img/4.jpg",original:"img/4.jpg",description:"Image 4 description"},{preview:"img/5.jpg",original:"img/5.jpg",description:"Image 5 description"},{preview:"img/6.jpg",original:"img/6.jpg",description:"Image 6 description"},{preview:"img/7.jpg",original:"img/7.jpg",description:"Image 7 description"},{preview:"img/8.jpg",original:"img/8.jpg",description:"Image 8 description"},{preview:"img/9.jpg",original:"img/9.jpg",description:"Image 9 description"}],p=document.querySelector(".gallery"),d=m.map(({preview:t,original:r,description:n})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${r}">
        <img
          class="gallery-image"
          src="${t}"
          data-source="${r}"
          alt="${n}"
        />
      </a>
    </li>`).join("");p.innerHTML=d;new c(".gallery a",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250,overlay:!0});const l="feedback-form-state";let o={email:"",message:""};const a=document.querySelector(".feedback-form");a&&(y(),a.addEventListener("input",u),a.addEventListener("submit",f));function u(t){o[t.target.name]=t.target.value.trim(),localStorage.setItem(l,JSON.stringify(o))}function f(t){t.preventDefault();const{email:r,message:n}=o;if(r===""||n===""){alert("Fill please all fields");return}console.log(o),localStorage.removeItem(l),o={email:"",message:""},a.reset()}function y(){const t=localStorage.getItem(l);t&&(o=JSON.parse(t),a.elements.email.value=o.email,a.elements.message.value=o.message)}
//# sourceMappingURL=index.js.map
